name: Deploy Chatbot

on:
  push:
    branches:
      - ayush

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject API Key
        run: |
          echo "window.API_KEY = '${{ secrets.OPENAI_API_KEY }}';" > api-key.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Inject API key as an environment variable

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
